import { NotificationData } from "./Notificationsinerfaces";

export const SampleData: NotificationData[] = [
  {
    guid: "1234-5678-9101",
    messageGroupGuid: "abcd-efgh-ijkl",
    dateSent: "2022-01-01T00:00:00Z",
    dateViewed: "2022-01-02T00:00:00Z",
    dateCompleted: "2022-01-03T00:00:00Z",
    dateArchived: "2022-01-04T00:00:00Z",
    sender: "John Doe@Massload.com",
    mainRecipient: "Jane Doe@Massload.com",
    allRecipients: "John  ",
    originatingApp: "Sample App",
    messageBody: "This is a sample message body.",
    messageTitle: "Sample Message Title",
    messageType: "info",
    messageOwner: true,
    messageUrl: "http://example.com/sample-message",
    messageId: "msg1234",
    roomName: "room1",
    messageStatus: "NEW",
    messagePriority: false,
    messageVisible: true,
    //  "messageSubject": "Sample Message Subject"
  },

  {
    guid: "1234-5678-9103",
    messageGroupGuid: "abcd-efgh-ijkl",
    dateSent: "2024-03-25T18:38:39.5557185Z",
    dateViewed: "2022-01-10T00:00:00Z",
    dateCompleted: "2022-01-11T00:00:00Z",
    dateArchived: "2022-01-12T00:00:00Z",
    sender: "Charlie@Massload.com",
    mainRecipient: "David@Massload.com",
    allRecipients: "Charlie  ",
    originatingApp: "Yet Another App",
    messageBody: "This is yet another sample message body.",
    messageTitle: "Yet Another Sample Message Title",
    messageType: "error",
    messageOwner: true,
    messageUrl: "http://example.com/yet-another-sample-message",
    messageId: "msg1236",
    roomName: "room1",
    messageStatus: "VIEWED",
    messagePriority: false,
    messageVisible: true,
    // "messageSubject": "Yet Another Sample Message Subject"
  },

  {
    guid: "1234-5678-9104",
    messageGroupGuid: "abcd-efgh-ijkl",
    dateSent: "2024-03-25T18:38:39.5557185Z",
    dateViewed: "2022-01-10T00:00:00Z",
    dateCompleted: "2022-01-11T00:00:00Z",
    dateArchived: "2022-01-12T00:00:00Z",
    sender: "Charlie@Massload.com",
    mainRecipient: "David@Massload.com",
    allRecipients: "Charlie  ",
    originatingApp: "Yet Another App",
    messageBody: "This is yet another sample message body.",
    messageTitle: "Yet Another Sample Message Title",
    messageType: "error",
    messageOwner: true,
    messageUrl: "http://example.com/yet-another-sample-message",
    messageId: "msg1236",
    roomName: "room1",
    messageStatus: "DONE",
    messagePriority: false,
    messageVisible: false,
    // "messageSubject": "Yet Another Sample Message Subject"
  },
];
